In [ ]:
# NumPy

In [ ]:
# Import Numpy

In [1]:
import numpy as np

In [ ]:
# From a Python List

In [2]:
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [ ]:
# From a Python Tuple

In [3]:
arr=np.array((10,20,30,40))
print(arr)

[10 20 30 40]


In [ ]:
# Range of Numbers

In [4]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [6]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Evenly Spaced Number

In [8]:
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# All Zeroes

In [9]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
# All Ones

In [10]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
# Same Number

In [11]:
arr=np.full(6,7)
print(arr)

[7 7 7 7 7 7]


In [ ]:
# Identity Matrix

In [12]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Random Values 0-1

In [14]:
arr=np.random.rand(5)
print(arr)

[0.31103823 0.45028887 0.63253257 0.90511998 0.6996993 ]


In [ ]:
# Random Integer

In [15]:
arr=np.random.randint(5)
print(arr)

3


In [ ]:
# Garbage values/uninitialized Array

In [16]:
arr=np.empty(4)
print(arr)

[4.9e-323 9.9e-323 1.5e-322 2.0e-322]


In [ ]:
# 2D Array

In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Indexing

In [18]:
arr=np.array([10,20,30,40])
print(arr[0])

10


In [ ]:
# accessing last value

In [19]:
print(arr[-1])

40


In [20]:
print(arr[1])

20


In [ ]:
#Slicing

In [21]:
print(arr[1:3])

[20 30]


In [ ]:
# Slice from BEginning

In [22]:
print(arr[:3])

[10 20 30]


In [23]:
print(arr[:4])

[10 20 30 40]


In [ ]:
# Slicing Till End

In [24]:
print(arr[1:])

[20 30 40]


In [27]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [28]:
print(arr2d[1][2])

6


In [ ]:
# Slice Row

In [30]:
print(arr2d[0])

[1 2 3]


In [ ]:
# Slice Column

In [31]:
print(arr2d[:,1])

[2 5]


In [ ]:
# Mathemat

In [32]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [33]:
print(arr+10)

[11 12 13 14]


In [34]:
print(arr-1)

[0 1 2 3]


In [35]:
print(arr**2)

[ 1  4  9 16]


In [36]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(arr1+arr2)

[5 7 9]


In [37]:
arr=np.array([10,20,30,40])
print(arr[arr>20])

[30 40]


In [39]:
print(np.sum(arr))

100


In [40]:
print(np.max(arr))

40


In [41]:
print(np.mean(arr))

25.0


In [42]:
print(np.min(arr))

10


In [43]:
print(np.max(arr)-np.min(arr))

30


In [44]:
arr=np.array([2,4,6])
print(arr*2)

[ 4  8 12]


In [45]:
arr=np.array([10,25,5,30])
print(arr[arr>15])

[25 30]


In [48]:
arr=np.array([5,-2,7,-9])
arr[arr<0]=1
print(arr)

[5 1 7 1]


In [50]:
arr=np.array([35,78,45,90])
result=np.where(arr>=40,"Pass","fail")
print(result)

['fail' 'Pass' 'Pass' 'Pass']


In [51]:
arr=np.array([1200,4500,8000,600])
arr[arr>4000]=0
print(arr)

[1200    0    0  600]


In [ ]:
15,22,10,36

In [59]:
arr=np.array([35,78,99,54,60])
passed=arr>=40
print(np.sum(passed))

4


In [61]:
arr=np.array([45,60,32,77,85])
age=np.where(arr>=60,"Senior","Adult")
print(age)

['Adult' 'Senior' 'Adult' 'Senior' 'Senior']


In [62]:
celsius=np.array([0,20,30,40])
fahrenheit=(celsius*9/5)+32
print(fahrenheit)

[ 32.  68.  86. 104.]


In [63]:
arr=np.array([10,15,27,22,36])
print(arr[arr%2 !=0])

[15 27]


In [64]:
arr=np.array([2,6,-5,4,-3])
arr[arr>0]=arr[arr>0]**2
print(arr)

[ 4 36 -5 16 -3]
